### ISSUE TITLE
Bogeys Breakfast with Santa

### ISSUE THREAD

**Issue by derekober** [hhgr/BogeyMacaws#4]
Adam,

I moved the old Breakfast with Santa page to the "specials" tab on BogeyMacaws.com
But the info on that page does not appear when I attempt to edit it for the new info. Would you prefer I pass the updated info to you or can you direct me to where I can access the old?

**Comment by AdamChlan** [comment]
Derek, I have fixed this up so you can edit it. That page must have been in draft mode when I did the conversion, so it didn’t get updated. Let me know if you need anything else.
